export default [
  {
    id: '0',
    value: require('./assets/img/hsbc.png'),
    title: 'HSBC',
    titleDescription: 'Euro Account',
    price: '€2,020',
    priceBold: '$2,240',
  },
  {
    id: '1',
    value: require('./assets/img/credit.png'),
    title: 'Credit Suisse',
    titleDescription: 'USD Custody',
    price: '$1,340',
    priceBold: '$1,340',
  },
  {
    id: '2',
    value: require('./assets/img/bnb.png'),
    title: 'UBS',
    titleDescription: 'CHF Account',
    price: 'CHF 1,471',
    priceBold: '$1,500',
  },
  {
    id: '3',
    value: require('./assets/img/btc.png'),
    title: 'BTC',
    titleDescription: 'Bitcoin Wallet',
    price: 'Ƀ0,093',
    priceBold: '$945',
  },
  {
    id: '4',
    value: require('./assets/img/ltc.png'),
    title: 'LTC',
    titleDescription: 'Litecoin Wallet',
    price: 'Ł0,014',
    priceBold: '$240',
  },
  {
    id: '5',
    value: require('./assets/img/bch.png'),
    title: 'BCH',
    titleDescription: 'Bitcion Cash Wallet',
    price: 'Ƀ0,131',
    priceBold: '$2,240',
  },
  {
    id: '6',
    value: require('./assets/img/hsbc.png'),
    title: 'HSBC',
    titleDescription: 'Euro Account',
    price: '€2,020',
    priceBold: '$2,240',
  },
  {
    id: '7',
    value: require('./assets/img/credit.png'),
    title: 'Credit Suisse',
    titleDescription: 'USD Custody',
    price: '$1,340',
    priceBold: '$1,340',
  },
  {
    id: '8',
    value: require('./assets/img/bnb.png'),
    title: 'UBS',
    titleDescription: 'CHF Account',
    price: 'CHF 1,471',
    priceBold: '$1,500',
  },
  {
    id: '9',
    value: require('./assets/img/btc.png'),
    title: 'BTC',
    titleDescription: 'Bitcoin Wallet',
    price: 'Ƀ0,093',
    priceBold: '$945',
  },
  {
    id: '10',
    value: require('./assets/img/ltc.png'),
    title: 'LTC',
    titleDescription: 'Litecoin Wallet',
    price: 'Ł0,014',
    priceBold: '$240',
  },
  {
    id: '11',
    value: require('./assets/img/bch.png'),
    title: 'BCH',
    titleDescription: 'Bitcion Cash Wallet',
    price: 'Ƀ0,131',
    priceBold: '$2,240',
  },
];
